version: 5.1.0
variant: cyberpunk
logo: /img/logo.svg
head:
  favicon: /favicon.svg
  manifest:
    name: 刘念的个人博客
    short_name: 个人博客
    start_url: https://liunian.js.org/
    theme_color:
    background_color:
    display: standalone
    icons:
      - src: /img/icon.png
        sizes: 144x144
        type: image/png
  open_graph:
    title:
    type: blog
    url:
    image:
    site_name:
    author:
    description:
    twitter_card:
    twitter_id:
    twitter_site:
    google_plus:
    fb_admins:
    fb_app_id:
  structured_data:
    title:
    description:
    url:
    author:
    publisher:
    publisher_logo:
    image:
  meta:
    - ""
  rss:
navbar:
  menu:
    主页: /
    归档: /archives
    分类: /categories
    标签: /tags
    关于: https://www.2077tech.com/
  links:
    GitHub:
      icon: fab fa-github
      url: https://github.com/liunnn1994
footer:
  links:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution 4.0 International:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    GitHub:
      icon: fab fa-github
      url: https://github.com/liunnn1994
article:
  highlight:
    theme: monokai
    clipboard: true
    fold: unfolded
  readtime: true
  update_time: true
  licenses:
    Creative Commons:
      icon: fab fa-creative-commons
      url: https://creativecommons.org/
    Attribution:
      icon: fab fa-creative-commons-by
      url: https://creativecommons.org/licenses/by/4.0/
    Noncommercial:
      icon: fab fa-creative-commons-nc
      url: https://creativecommons.org/licenses/by-nc/4.0/
search:
  type: insight
  index_pages: true
comment:
  type: gitalk
  client_id: a776b8ece31855f47113
  client_secret: 2df1e3beabc83813855e4de796119f31c4fad91e
  repo: liunnn1994.github.io
  owner: liunnn1994
  admin:
    - liunnn1994
  language: zh-CN
donates:
  - type: afdian
    url: ""

  - type: alipay
    qrcode: /img/alipay.jpg
  - type: wechat
    qrcode: /img/wechat.png
share:
  type: sharethis
  install_url: https://platform-api.sharethis.com/js/sharethis.js#property=63bbd61a38e123001920dbec&product=inline-share-buttons&source=platform
sidebar:
  left:
    sticky: false
  right:
    sticky: false
widgets:
  - position: left
    type: profile
    author: Liu
    author_title: 刘念的个人博客
    location: 北京
    avatar: img/my_avatar.png
    avatar_rounded: false
    gravatar:
    follow_link: https://github.com/liunnn1994
    social_links:
      Github:
        icon: fab fa-github
        url: https://github.com/liunnn1994
  - position: left
    type: toc
    index: true
    collapsed: true
    depth: 3
  - position: left
    type: links
    links:
      GitHub: https://github.com/liunnn1994
  - position: left
    type: categories
  - position: left
    type: recent_posts
  - position: left
    type: archives
  - position: left
    type: tags
plugins:
  animejs: true
  back_to_top: true
  baidu_analytics:
    tracking_id:
  bing_webmaster:
    tracking_id:
  busuanzi: false
  cnzz:
    id:
    web_id:
  cookie_consent:
    type: info
    theme: edgeless
    static: false
    position: bottom-left
    policyLink: https://www.cookiesandyou.com/
  gallery: true
  google_analytics:
    tracking_id:
  hotjar:
    site_id:
  katex: false
  mathjax: false
  outdated_browser: false
  progressbar: true
  statcounter:
    project:
    security:
  twitter_conversion_tracking:
    pixel_id:
providers:
  cdn: jsdelivr
  fontcdn: google
  iconcdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css
